services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
    volumes:
      - /mnt/llms/ollama:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped
